### ISSUE TITLE
include documentation on remapping to an (Open)IFS grid

### ISSUE THREAD

**Issue by etiennesky** [JJDHooghiem/vremap#1]
the subject speaks for itself, it would be great to provide brief instructions on how to remap the output of this tool to the reduced Gaussian/Octahedral grid of (Open)IFS.  Perhaps as well a link to the page describing this grid would be helpful. https://confluence.ecmwf.int/display/OIFS/4.+OpenIFS%3A+Grid+and+Resolution

**Comment by JJDHooghiem** [comment]
Hi, 

I've added an `examples` directory, with a shell script showing how to perform the task you mentioned. The README is updated with a reference to the shell script and the page you've given me (thanks for that). I take it that is (maybe the minimum) what you had in mind? let me know whether this closes the issue...

**Comment by etiennesky** [comment]
yes that´s useful!
